### ISSUE TITLE
Perform CRUD operations by using RTK Query

### ISSUE THREAD

**Issue by codek-tech9** [Muhammad-Usman36/RTKScreens#1]
Create a new screen and perform CRUD operations

- [ ]  Create
- [ ]  Read
- [ ]  Updated
- [ ]  Delete
- [ ]  use flatlist to display data
- [ ]  Add edit and delete icons on each data and perform functionality accordingly.

**Comment by Muhammad-Usman36** [comment]
1.	Task Name: Create 2 Screen Enable navigation between the
•	Status: Completed
•	Note:
2.	Task Name: Show Data on Home Screen
•	Status: Completed
•	Note:
3.	Task Name: Delete Data on Home Screen
•	Status: Completed
•	Note:
4.	Task Name: Eidt data On Home Screen
•	Status: Completed
•	Note:
5.	Task Name: Use Icons to edit and delete
•	Status: Completed
•	Note:
6.	Task Name: Navigation with button to move on Add screen
•	Status: Completed
•	Note:
7.	Task Name: Data Addition function performed on Add Screen
•	Status: Completed
•	Note:
8.	Task Name: navigate from the Add data screen to the Home Screen
•	Status: Completed
•	Note:
9.	Task Name: On the Home Screen Create A Text Input field
•	Status: Completed
•	Note:
10.	Task Name: When we add data in Text input fried related data wail come on top
•	Status: Completed
•	Note: work on the base of name and email
11. Task Name: when press the edit button a new screen aper with filled data fields to update data
Status: Complete                                                                                                                                                                                                                                                                                                                          Note:          








https://github.com/codektech/RTKScreens/assets/146926435/00acecd6-d7c8-46f7-8903-fb3c0f72ed23

**Comment by codek-tech9** [comment]
@hamza4213 please review it.
