### ISSUE TITLE
Automation Testing

### ISSUE THREAD

**Issue by codek-tech9** [Muhammad-Usman36/RTKScreens#4]
https://appium.io/docs/en/latest/quickstart/test-js/

- [x]  Make an appium project from scratch
- [x]  Make an apk and start testing it through automation

**Comment by Muhammad-Usman36** [comment]
- Create an Appium project from scratch                               
-

**Comment by Muhammad-Usman36** [comment]
Task Complete I test the Redux toolkit  App that was created in my last project

https://github.com/codektech/RTKScreens/assets/146926435/5485b4c8-c61e-4428-9807-32c15a05f4e8
